### ISSUE TITLE
n_views error

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#137]
I have four cameras. When using a 5-cam-AVG-pre-trained weight file, 

**1. if I set n_views=4 doing dannce-train, there is a very common error:** 
`Could not load weights for finetune (likely because you are finetuning a previously finetuned network). Attempting to finetune from a full finetune model file.
Traceback (most recent call last):
  File "f:\testdannce120\dannce\dannce\interface.py", line 1125, in dannce_train
    *fargs
  File "f:\testdannce120\dannce\dannce\engine\nets.py", line 1177, in finetune_AVG
    model = renameLayers(model, weightspath)
  File "f:\testdannce120\dannce\dannce\engine\nets.py", line 1405, in renameLayers
    model.load_weights(weightspath, by_name=True)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2324, in load_weights
    f, self.layers, skip_mismatch=skip_mismatch)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 768, in load_weights_from_hdf5_group_by_name
    layer, weight_values, original_keras_version, original_backend)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 404, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\numpy\core\fromnumeric.py", line 660, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\envs\tfnew_25\Scripts\dannce-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-train')())
  File "f:\testdannce120\dannce\dannce\cli.py", line 66, in dannce_train_cli
    dannce_train(params)
  File "f:\testdannce120\dannce\dannce\interface.py", line 1131, in dannce_train
    *fargs
  File "f:\testdannce120\dannce\dannce\engine\nets.py", line 1255, in finetune_fullmodel_AVG
    for layer in model.layers[1].layers:
AttributeError: 'Conv3D' object has no attribute 'layers'
`
#######################################################
**2. if I set n_views=5, after duplicate Camera1, the dannce-train processing runs successfully; however, dannce-predict processing does not work, an error like:**

`Initializing Network...
Loading model from .\DANNCE\train_results\AVG\weights.17-67.87837.hdf5
Traceback (most recent call last):
  File "E:\anaconda\envs\tfnew_25\Scripts\dannce-predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "f:\testdannce120\dannce\dannce\cli.py", line 54, in dannce_predict_cli
    dannce_predict(params)
  File "f:\testdannce120\dannce\dannce\interface.py", line 1543, in dannce_predict
    "centered_euclidean_distance_3D": losses.centered_euclidean_distance_3D,
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\saving\save.py", line 202, in load_model
    compile)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 199, in load_model_from_hdf5
    training_config, custom_objects), from_serialized=True)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 454, in compile
    masks=self._prepare_output_masks())
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1976, in _handle_metrics
    target, output, output_mask))
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1925, in _handle_per_output_metrics
    with backend.name_scope(metric_name):
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\backend.py", line 1039, in name_scope
    return ops.name_scope_v2(name)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\framework\ops.py", line 6647, in __init__
    raise ValueError("name for name_scope must be a string.")
ValueError: name for name_scope must be a string.`

Have anyone met the errors before? Many thanks if give me some suggestions to fix them.

**Comment by spoonsso** [comment]
This looks like the same as #147 -- for the more recent errors, are you also trying to use a duplicate view? Please continue discussion in #147.
