### ISSUE TITLE
ValueError: name for name_scope must be a string when doing dannce-predict.

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#147]
`Initializing Network...
Loading model from .\DANNCE\train_results\MAX\weights.1185-0.00001.hdf5
Traceback (most recent call last):
  File "E:\anaconda\envs\danncetest\Scripts\dannce-predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "f:\test_dannce\dannce\dannce\cli.py", line 54, in dannce_predict_cli
    dannce_predict(params)
  File "f:\test_dannce\dannce\dannce\interface.py", line 1534, in dannce_predict
    "centered_euclidean_distance_3D": losses.centered_euclidean_distance_3D,
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\keras\saving\save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 194, in load_model_from_hdf5
    training_config, custom_objects))
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 451, in compile
    masks=self._prepare_output_masks())
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1955, in _handle_metrics
    target, output, output_mask))
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1904, in _handle_per_output_metrics
    with K.name_scope(metric_name):
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\keras\backend.py", line 912, in name_scope
    return ops.name_scope_v2(name)
  File "E:\anaconda\envs\danncetest\lib\site-packages\tensorflow\python\framework\ops.py", line 6593, in __init__
    raise ValueError("name for name_scope must be a string.")
ValueError: name for name_scope must be a string.`

So i put a pdb in 'File "f:\test_dannce\dannce\dannce\interface.py", line 1534, in dannce_predict;

(Pdb) from tensorflow.keras.models import load_model

(Pdb) custom_objects={ "ops": ops, "slice_input": nets.slice_input, "mask_nan_keep_loss": losses.mask_nan_keep_loss,"mask_nan_l1_loss": losses.mask_nan_l1_loss,"euclidean_distance_3D": losses.euclidean_distance_3D,"centered_euclidean_distance_3D": losses.centered_euclidean_distance_3D,}
(Pdb) model = load_model(mdl_file,custom_objects)

*** ValueError: name for name_scope must be a string.

`(Pdb) mdl_file,
('.\\DANNCE\\train_results\\MAX\\weights.1185-0.00001.hdf5',)`

`(Pdb) custom_objects 
{'ops': <module 'dannce.engine.ops' from 'f:\\test_dannce\\dannce\\dannce\\engine\\ops.py'>, 'slice_input': <function slice_input at 0x000001D3D4968AF8>, 'mask_nan_keep_loss': <function mask_nan_keep_loss at 0x000001D3D4950F78>, 'mask_nan_l1_loss': <function mask_nan_l1_loss at 0x000001D3D49684C8>, 'euclidean_distance_3D': <function euclidean_distance_3D at 0x000001D3D4968828>, 'centered_euclidean_distance_3D': <function centered_euclidean_distance_3D at 0x000001D3D49688B8>}`

Does anyone know what happened? and any solutions? thank you so much @davidhildebrand @spoonsso

**Comment by spoonsso** [comment]
Hi @yuan0821, can you tell us a bit more about what led to this? What branch are you using? If it was working for you before, what did you change recently?

**Comment by Raunakbasu86** [comment]
Hi I am having the same problem. Was this issue resolved?

```
(dannce-mod) PS C:\Users\owner\src\code\github\dannce\projects\Rat025_15Jul2025> dannce-predict .\main_dannce_config.yaml
2025-09-21 15:14:51.505457: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
io_config not found in io.yaml file, falling back to main config
new_n_channels_out not found in io.yaml file, falling back to main config
batch_size not found in io.yaml file, falling back to main config
downfac not found in io.yaml file, falling back to main config
mono not found in io.yaml file, falling back to main config
n_views not found in io.yaml file, falling back to main config
crop_height not found in io.yaml file, falling back to main config
crop_width not found in io.yaml file, falling back to main config
epochs not found in io.yaml file, falling back to main config
net_type not found in io.yaml file, falling back to main config
train_mode not found in io.yaml file, falling back to main config
num_validation_per_exp not found in io.yaml file, falling back to main config
vol_size not found in io.yaml file, falling back to main config
nvox not found in io.yaml file, falling back to main config
start_sample not found in io.yaml file, falling back to main config
max_num_samples not found in io.yaml file, falling back to main config
expval not found in io.yaml file, falling back to main config
com_train_dir set to: .\COM\train_results\
com_predict_dir set to: .\COM\predict_results\
com_predict_weights set to: C:\Users\owner\src\code\github\dannce\projects\Rat025_15Jul2025\COM\train_results\fullmodel_weights\fullmodel_end.hdf5
dannce_train_dir set to: .\DANNCE\train_results\AVG\
dannce_predict_dir set to: .\DANNCE\predict_results\
dannce_predict_model set to: C:\Users\owner\src\code\github\dannce\projects\Rat025_15Jul2025\DANNCE\train_results\AVG\fullmodel_weights\weights.1200-74692.03125.hdf5
exp set to: [{'label3d_file': 'C:\\Users\\owner\\src\\code\\github\\dannce\\projects\\Rat025_15Jul2025/20250916_211332_Label3D_dannce.mat'}]
io_config set to: io.yaml
new_n_channels_out set to: 3
batch_size set to: 2
downfac set to: 2
mono set to: True
n_views set to: 4
crop_height set to: [0, 1152]
crop_width set to: [0, 1920]
epochs set to: 1200
net_type set to: AVG
train_mode set to: new
num_validation_per_exp set to: 4
vol_size set to: 125
nvox set to: 64
start_sample set to: 20000
max_num_samples set to: 1000
expval set to: False
base_config set to: .\main_dannce_config.yaml
viddir set to: videos
camnames set to: None
n_channels_out set to: 3
sigma set to: 10
verbose set to: 1
net set to: None
gpu_id set to: 0
immode set to: vid
mirror set to: False
start_batch set to: 0
com_fromlabels set to: False
medfilt_window set to: None
com_file set to: None
new_last_kernel_size set to: [3, 3, 3]
n_layers_locked set to: 2
vmin set to: None
vmax set to: None
interp set to: nearest
depth set to: False
comthresh set to: 0
weighted set to: False
com_method set to: median
cthresh set to: None
channel_combo set to: None
predict_mode set to: torch
dannce_finetune_weights set to: None
from_weights set to: None
write_npy set to: None
loss set to: mask_nan_keep_loss
n_channels_in set to: None
extension set to: None
vid_dir_flag set to: None
num_train_per_exp set to: None
chunks set to: None
lockfirst set to: None
load_valid set to: None
augment_hue set to: False
augment_brightness set to: False
augment_hue_val set to: 0.05
augment_bright_val set to: 0.05
augment_rotation_val set to: 5
drop_landmark set to: None
raw_im_h set to: None
raw_im_w set to: None
n_instances set to: 1
use_npy set to: False
data_split_seed set to: None
valid_exp set to: None
metric set to: ['euclidean_distance_3D']
lr set to: 0.001
rotate set to: True
augment_continuous_rotation set to: False
com_thresh set to: None
cam3_train set to: None
debug_volume_tifdir set to: None
dannce_predict_vol_tifdir set to: None
n_rand_views set to: 0
rand_view_replace set to: True
multi_gpu_train set to: False
heatmap_reg set to: False
heatmap_reg_coeff set to: 0.01
save_pred_targets set to: False
Using the following *dannce.mat files: .\20250916_211332_Label3D_dannce.mat
Setting vid_dir_flag to True.
Setting extension to .mp4.
Setting chunks to {'Camera1': array([0]), 'Camera2': array([0]), 'Camera3': array([0]), 'Camera4': array([0])}.
Setting n_channels_in to 3.
Setting raw_im_h to 1200.
Setting raw_im_w to 1920.
Setting expval to True.
Setting net to unet3d_big_expectedvalue.
Setting maxbatch to 500.
Setting start_batch to 10000.
Setting vmin to -62.5.
Setting vmax to 62.5.
Using the following *dannce.mat files: .\20250916_211332_Label3D_dannce.mat
Using torch predict mode
Using camnames: ['Camera1', 'Camera2', 'Camera3', 'Camera4']
Experiment 0 using com3d: .\20250916_211332_Label3D_dannce.mat
Removed 0 samples from the dataset because they either had COM positions over cthresh, or did not have matching sampleIDs in the COM file
Saving 3D COM to .\DANNCE\predict_results\com3d_used.mat
None
2025-09-21 15:14:54.287103: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-21 15:14:54.288866: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2025-09-21 15:14:54.303745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA RTX A2000 12GB computeCapability: 8.6
coreClock: 1.2GHz coreCount: 26 deviceMemorySize: 11.99GiB deviceMemoryBandwidth: 268.26GiB/s
2025-09-21 15:14:54.303876: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2025-09-21 15:14:54.303925: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2025-09-21 15:14:54.303963: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2025-09-21 15:14:54.303991: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2025-09-21 15:14:54.304018: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2025-09-21 15:14:54.304045: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2025-09-21 15:14:54.304114: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2025-09-21 15:14:54.304166: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2025-09-21 15:14:54.304241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2025-09-21 15:14:54.735571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2025-09-21 15:14:54.735691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2025-09-21 15:14:54.735738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2025-09-21 15:14:54.736047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5526 MB memory) -> physical GPU (device: 0, name: NVIDIA RTX A2000 12GB, pci bus id: 0000:01:00.0, compute capability: 8.6)
2025-09-21 15:14:54.737246: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Init took 1.6081359386444092 sec.
Initializing Network...
Loading model from C:\Users\owner\src\code\github\dannce\projects\Rat025_15Jul2025\DANNCE\train_results\AVG\fullmodel_weights\weights.1200-74692.03125.hdf5
2025-09-21 15:14:56.340278: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Traceback (most recent call last):
  File "C:\Users\owner\miniconda3\envs\dannce-mod\Scripts\dannce-predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "c:\users\owner\src\code\github\dannce\dannce\cli.py", line 54, in dannce_predict_cli
    dannce_predict(params)
  File "c:\users\owner\src\code\github\dannce\dannce\interface.py", line 1534, in dannce_predict
    "centered_euclidean_distance_3D": losses.centered_euclidean_distance_3D,
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\keras\saving\save.py", line 207, in load_model
    compile)
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 200, in load_model_from_hdf5
    training_config, custom_objects))
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\training\tracking\base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 450, in compile
    masks=self._prepare_output_masks())
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1957, in _handle_metrics
    target, output, output_mask))
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1906, in _handle_per_output_metrics
    with K.name_scope(metric_name):
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\keras\backend.py", line 935, in name_scope
    return ops.name_scope_v2(name)
  File "C:\Users\owner\miniconda3\envs\dannce-mod\lib\site-packages\tensorflow\python\framework\ops.py", line 6612, in __init__
    raise ValueError("name for name_scope must be a string.")
ValueError: name for name_scope must be a string.
```
