### ISSUE TITLE
How to use "finetune" to train the DANNCE network

### ISSUE THREAD

**Issue by Shaked198** [spoonsso/dannce#50]
We are trying to use the rat.max weights to finetune our dannce model. We used either 5 or 14 labels, but can't get dannce-train to work. 

In the dannce_config file we tried to use the following settings:
new_n_channels_out: 5
train_mode: finetune
dannce_finetune_weights: C:\dannce-1.2.0\demo\markerless_mouse_1\DANNCE\weights\weights.rat.MAX
net_type: AVG

This is the error we get:
Traceback (most recent call last):
  File "C:\Users\YoramG\Anaconda3\envs\dannce\Scripts\dannce-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-train')())
  File "c:\dannce-1.2.0\dannce\cli.py", line 66, in dannce_train_cli
    dannce_train(params)
  File "c:\dannce-1.2.0\dannce\interface.py", line 1129, in dannce_train
    gridsize=gridsize,
  File "c:\dannce-1.2.0\dannce\engine\nets.py", line 1125, in finetune_AVG
    model = renameLayers(model, weightspath)
  File "c:\dannce-1.2.0\dannce\engine\nets.py", line 1204, in renameLayers
    model.load_weights(weightspath, by_name=True)
  File "C:\Users\YoramG\Anaconda3\envs\dannce\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2209, in load_weights
    f, self.layers, skip_mismatch=skip_mismatch)
  File "C:\Users\YoramG\Anaconda3\envs\dannce\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 759, in load_weights_from_hdf5_group_by_name
    layer, weight_values, original_keras_version, original_backend)
  File "C:\Users\YoramG\Anaconda3\envs\dannce\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 403, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "C:\Users\YoramG\Anaconda3\envs\dannce\lib\site-packages\numpy\core\fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "C:\Users\YoramG\Anaconda3\envs\dannce\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array

**Comment by diegoaldarondo** [comment]
Could you please share your dannce config?

**Comment by morbent** [comment]
[main_dannce_config.txt](https://github.com/spoonsso/dannce/files/6797581/main_dannce_config.txt)

Here it is.

**Comment by spoonsso** [comment]
Can you try setting your config to use `n_channels_out: 20`. Keep `new_n_channels_out: 14` (or 5).

If you still get the error, please send me the full terminal output from dannce-train (i.e. including all of the statements about parameters being set).

**Comment by spoonsso** [comment]
p.s. I would toggle `augment_brightness` and `augment_continuous_rotation` to False, unless you are willing to spend some time exploring the space of values for `augment_brightness_val` or `augment_continuous_rotation`. Recent experiments with the default augmentation values showed reduced performance when finetuning on mouse.
