### ISSUE TITLE
ValueError: generator already executing.

### ISSUE THREAD

**Issue by Spartan859** [spoonsso/dannce#59]
When I ran dannce-predict, it gave the following message:

> Traceback (most recent call last):
  File "/home/qiushou/anaconda3/envs/dannce/bin/dannce-predict", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "/home/xulab/Documents/dannce/dannce/cli.py", line 54, in dannce_predict_cli
    dannce_predict(params)
  File "/home/xulab/Documents/dannce/dannce/interface.py", line 1577, in dannce_predict
    n_chn,
  File "/home/xulab/Documents/dannce/dannce/engine/inference.py", line 696, in infer_dannce
    ims = generator.__getitem__(i)
  File "/home/xulab/Documents/dannce/dannce/engine/generator.py", line 966, in __getitem__
    X, y = self.__data_generation(list_IDs_temp)
  File "/home/xulab/Documents/dannce/dannce/engine/generator.py", line 1258, in __data_generation
    result = self.threadpool.starmap(self.project_grid, arglist)
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/xulab/Documents/dannce/dannce/engine/generator.py", line 1028, in project_grid
    extension=self.extension,
  File "/home/xulab/Documents/dannce/dannce/engine/video.py", line 238, in load_vid_frame
    im = vid.get_data(frame_num).astype("uint8") if self.predict_flag \
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/site-packages/imageio/core/format.py", line 346, in get_data
    im, meta = self._get_data(index, **kwargs)
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 384, in _get_data
    result, is_new = self._read_frame()
  File "/home/qiushou/anaconda3/envs/dannce/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 486, in _read_frame
    s = self._read_gen.__next__()
ValueError: generator already executing

**Comment by yuan0821** [comment]
hi @Spartan859 
I also met the error. may I ask how to fix it? thank you!
