### ISSUE TITLE
UnboundLocalError: local variable 'batch_outputs' referenced before assignment

### ISSUE THREAD

**Issue by Spartan859** [spoonsso/dannce#66]
> Epoch 150/150
42/42 [==============================] - 13s 321ms/step - loss: 5.8465e-05
Traceback (most recent call last):
  File "/home/xuchun/.conda/envs/dannce/bin/com-train", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'com-train')())
  File "/home/xuchun/dannce/dannce/cli.py", line 42, in com_train_cli
    com_train(params)
  File "/home/xuchun/dannce/dannce/interface.py", line 661, in com_train
    write_debug(trainData=False)
  File "/home/xuchun/dannce/dannce/interface.py", line 624, in write_debug
    label_out = model.predict(ims_valid, batch_size=1)
  File "/home/xuchun/.conda/envs/dannce/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/xuchun/.conda/envs/dannce/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1614, in predict
    all_outputs = nest.map_structure_up_to(batch_outputs, concat, outputs)
UnboundLocalError: local variable 'batch_outputs' referenced before assignment

When I finished training COM-finder, this happened.

How can I fix this?

**Comment by Spartan859** [comment]
By the way, this only happened when num_validation_per_exp is set to 0.
When I change it to 2, there is no errors.

**Comment by Spartan859** [comment]
> However, the more validation samples you use, the fewer samples you can use for the actual training. We recommend using num_validation_per_exp: 0 unless you are using over 100 samples per animal.

According to this in ur wiki.

**Comment by Spartan859** [comment]
Maybe this is because of the debug: True in com_config?

**Comment by spoonsso** [comment]
Yes, sorry. It is trying to save the predictions on the validation images when debug: True, but your ims_valid was empty because num_validation_per_exp.

**Comment by SwathiSheshadri** [comment]
I ran into the same issue after running several epochs of dannce-train. Would setting debug: False in the config file be sufficient to resolve this?

**Comment by spoonsso** [comment]
Yes, set debug to False.
