### ISSUE TITLE
ValueError: bad marshal data (unknown type data)

### ISSUE THREAD

**Issue by kantkantwuqh** [spoonsso/dannce#76]
Hi,

When I run `dannce-predict ../../configs/dannce_mouse_config.yaml`, I have the following ValueError
![valueerror](https://user-images.githubusercontent.com/90238063/139094700-d3490630-4128-4afa-9753-45a106c81843.png)
How should I deal with it? Thank you!

**Comment by kantkantwuqh** [comment]
I have tried deleting all .pyc files, and also reinstall tensorflow, but they didn't work

**Comment by kantkantwuqh** [comment]
> I have tried deleting all .pyc files, and also reinstall tensorflow, but they didn't work

These two methods are suggested on google, but didn't work for me

**Comment by spoonsso** [comment]
Hello! Can you please tell me more about your system and where exactly during `dannce-predict` the error was thrown?

**Comment by spoonsso** [comment]
@kantkantwuqh were you able to resolve this? If so, do you mind leave a brief explanation here in the issue thread in case someone else runs into thus problem in the future? Thanks!

**Comment by Rodgers-PAC-Lab** [comment]
I am having this problem too. I believe this happens when you try to load in the weights from a previous version of python or tensorflow using a new version of python or tensorflow. See here: https://github.com/keras-team/keras/issues/7440

This shows where it happens:
```
Loading model from ./DANNCE/train_results/AVG/weights.1200-12.77642.hdf5
2022-05-02 16:54:27.615732: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-02 16:54:27.615872: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.615970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.807GHz coreCount: 28 deviceMemorySize: 11.77GiB deviceMemoryBandwidth: 335.32GiB/s
2022-05-02 16:54:27.615996: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-05-02 16:54:27.616033: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-05-02 16:54:27.616043: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2022-05-02 16:54:27.616053: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-05-02 16:54:27.616061: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-05-02 16:54:27.616075: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-05-02 16:54:27.616086: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2022-05-02 16:54:27.616094: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-05-02 16:54:27.616130: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616210: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-05-02 16:54:27.616409: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-02 16:54:27.616458: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.807GHz coreCount: 28 deviceMemorySize: 11.77GiB deviceMemoryBandwidth: 335.32GiB/s
2022-05-02 16:54:27.616526: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-05-02 16:54:27.616537: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-05-02 16:54:27.616545: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2022-05-02 16:54:27.616552: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-05-02 16:54:27.616559: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-05-02 16:54:27.616567: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-05-02 16:54:27.616574: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2022-05-02 16:54:27.616582: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-05-02 16:54:27.616610: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616684: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-05-02 16:54:27.616750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-02 16:54:27.616754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2022-05-02 16:54:27.616757: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2022-05-02 16:54:27.616803: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616881: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-02 16:54:27.616936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10847 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6)
Traceback (most recent call last):
  File "/home/mouse/miniconda3/envs/dannce/bin/dannce-predict", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "/home/mouse/dev/dannce/dannce/cli.py", line 134, in dannce_predict_cli
    dannce_predict(params)
  File "/home/mouse/dev/dannce/dannce/interface.py", line 1395, in dannce_predict
    model = build_model(params, camnames)
  File "/home/mouse/dev/dannce/dannce/interface.py", line 1598, in build_model
    model = load_model(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 183, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 64, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2261, in from_config
    return functional.Functional.from_config(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 668, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1275, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1257, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1019, in from_config
    function = cls._parse_function_from_config(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1071, in _parse_function_from_config
    function = generic_utils.func_load(
  File "/home/mouse/miniconda3/envs/dannce/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 457, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

Here is info about my system:
dannce branch: release_development
```
cudatoolkit               11.1.74              h6bb024c_0    nvidia
numpy                     1.19.5                   pypi_0    pypi
python                    3.8.13               h12debd9_0  
pytorch                   1.8.2           py3.8_cuda11.1_cudnn8.0.5_0    pytorch-lts
tensorflow                2.4.0                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
torchaudio                0.8.2                      py38    pytorch-lts
torchvision               0.9.2                py38_cu111    pytorch-lts
```

I have to use CUDA >11 for my Ampere GPU, which means I had to use slightly newer versions of a lot of other things than the DANNCE install directions advice. I think this is probably the cause of my problems. thanks for any tips!

**Comment by Rodgers-PAC-Lab** [comment]
Update: dropping to python=3.7 but keeping everything else the same fixes this issue!
